{% set version = "0.1" %}

package:
  name: parla
  version: {{ version }}

build:
  noarch: python
  number: 7
  script: |
    cd $RECIPE_DIR || echo running in cmd
    cd %RECIPE_DIR% || echo running in bash
    cd ..
    "{{ PYTHON }}" -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - cupy
    - scipy
    - numba
    #- mpi4py

about:
  license: BSD
  summary: Parla tasking system.

extra:
  recipe-maintainers:
    - insertinterestingnamehere
