# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 9 * * *"
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  figure_9:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Runs launcher.py on all figures and app
      - name: Run Figure 9
        run: python3 examples/launcher.py --figure 9

  figure_11:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Run Figure 11
        run: python3 examples/launcher.py --figure 11
        
  figure_12:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Run Figure 12
        run: python3 examples/launcher.py --figure 12
        
  figure_13:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Run Figure 13
        run: python3 examples/launcher.py --figure 13
        
  figure_14:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Run Figure 14
        run: python3 examples/launcher.py --figure 14
